
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: solution.ipynb

import numpy as np
from helper_functions import *

def get_initial_means(array, k):
    """
    Picks k random points from the 2D array
    (without replacement) to use as initial
    cluster means

    params:
    array = numpy.ndarray[numpy.ndarray[float]] - m x n | datapoints x features

    k = int

    returns:
    initial_means = numpy.ndarray[numpy.ndarray[float]]
    """
    a = np.random.choice(len(array), k, replace=False)
    arr = array[a[:, None], :]
    arr = np.squeeze(arr, axis=1)
    return arr
########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def k_means_step(X, k, means):
    """
    A single update/step of the K-means algorithm
    Based on a input X and current mean estimate,
    predict clusters for each of the pixels and
    calculate new means.
    params:
    X = numpy.ndarray[numpy.ndarray[float]] - m x n | pixels x features (already flattened)
    k = int
    means = numpy.ndarray[numpy.ndarray[float]] - k x n

    returns:
    (new_means, clusters)
    new_means = numpy.ndarray[numpy.ndarray[float]] - k x n
    clusters = numpy.ndarray[int] - m sized vector
    """

    distances = []
    clusters = []
    new_means = []
#     calculate distances between means and all point and put distances into np array m
    for i in range(len(means)):
        d = np.linalg.norm(X-means[i], axis=1)
        distances.append(d)
    distances = np.array(distances)

#     find k index for each distance
    min_col_ids = np.argmin(distances, axis=0)
    distances = np.transpose(distances)

#     create k clusters
    for i in range(k):
        min_row_ids = np.argwhere(min_col_ids==np.ones(len(X))*i)
        c = np.take(X, min_row_ids, axis = 0)
        new_means.append(np.mean(c, axis = 0))
    new_means = np.array(new_means)
    new_means = np.squeeze(new_means, axis=1)

    return new_means, min_col_ids

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def k_means_segment(image_values, k=3, initial_means=None):
    """
    Separate the provided RGB values into
    k separate clusters using the k-means algorithm,
    then return an updated version of the image
    with the original values replaced with
    the corresponding cluster values.

    params:
    image_values = numpy.ndarray[numpy.ndarray[numpy.ndarray[float]]] - r x c x ch
    k = int
    initial_means = numpy.ndarray[numpy.ndarray[float]] or None

    returns:
    updated_image_values = numpy.ndarray[numpy.ndarray[numpy.ndarray[float]]] - r x c x ch
    """
    img_shape = image_values.shape
    if image_values.ndim == 3:
        image_values = np.reshape(image_values, (img_shape[0]*img_shape[1], 3))

#     get initial means
    if initial_means is None:
        initial_means = get_initial_means(image_values, k)

    n_iterations = 53
    shape = image_values.shape
    clusters = np.zeros([shape[1]])
    means_history = [initial_means]

#     run k means step to convergence
    for i in range(n_iterations):
        initial_means, clusters = k_means_step(image_values, k, initial_means)

#     segment image with mean values
    ones = np.ones((img_shape[0]*img_shape[1], 3))
    for i in range(k):
        mask = clusters == i
        mask = np.vstack((mask, mask, mask))
        mask = np.transpose(mask)
        prod = mask*ones*initial_means[i]
        if i == 0:
            img = prod
        else:
            img = img+prod

#     reshape image to original dimension
    img = np.reshape(img, (img_shape[0], img_shape[1], 3))

    return img
########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def initialize_parameters(X, k):
    """
    Return initial values for training of the GMM
    Set component mean to a random
    pixel's value (without replacement),
    based on the mean calculate covariance matrices,
    and set each component mixing coefficient (PIs)
    to a uniform values
    (e.g. 4 components -> [0.25,0.25,0.25,0.25]).

    params:
    X = numpy.ndarray[numpy.ndarray[float]] - m x n
    k = int

    returns:
    (MU, SIGMA, PI)
    MU = numpy.ndarray[numpy.ndarray[float]] - k x n
    SIGMA = numpy.ndarray[numpy.ndarray[numpy.ndarray[float]]] - k x n x n
    PI = numpy.ndarray[float] - k x 1
    """

    initial_means = get_initial_means(X, k)
    pi = np.ones((1,k))
    c = len(X)/np.sum(pi)
    pi = pi/np.sum(pi)

    prod = np.ones((len(X),1))
    for i in range(k):
        s = X-initial_means[i]
        if i == 0:
            sigma = [pi[0, i]*np.dot(np.transpose(s), s)/c]
        else:
            sigma = np.vstack((sigma, [pi[0, i]*np.dot(np.transpose(s), s)/c]))

    return initial_means, sigma, pi
########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################


def compute_sigma(X, MU):
    """
    Calculate covariance matrix, based in given X and MU values

    params:
    X = numpy.ndarray[numpy.ndarray[float]] - m x n
    MU = numpy.ndarray[numpy.ndarray[float]] - k x n

    returns:
    SIGMA = numpy.ndarray[numpy.ndarray[numpy.ndarray[float]]] - k x n x n
    """

    PI = np.ones((1, len(MU)))
    c = len(X)/np.sum(PI)
    PI = PI/np.sum(PI)

    for i in range(len(MU)):
        s = X-MU[i]
        if i == 0:
            sigma = [PI[0, i]*np.dot(np.transpose(s), s)]/c
        else:
            sigma = np.vstack((sigma, [PI[0, i]*np.dot(np.transpose(s), s)]/c))

    return sigma
########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################


def prob(x, mu, sigma):
    """Calculate the probability of x (a single
    data point or an array of data points) under the
    component with the given mean and covariance.
    The function is intended to compute multivariate
    normal distribution, which is given by N(x;MU,SIGMA).

    params:
    x = numpy.ndarray[float] or numpy.ndarray[numpy.ndarray[float]]
    mu = numpy.ndarray[float]
    sigma = numpy.ndarray[numpy.ndarray[float]]

    returns:
    probability = float or numpy.ndarray[float]
    """

    if np.shape(x) == (len(x),):
        x = np.reshape(x, (1, len(x)))
    diff = x - mu
    const = 1/np.power((2*np.pi), len(x[0])/2)
    s = np.power(np.linalg.det(sigma), -1/2)
    diff = np.array(diff, dtype='f')
    prod1 = np.array(np.dot(diff, np.linalg.inv(sigma)), dtype='f')
    prod2 = np.sum(np.multiply(prod1,diff), axis=1)
    ex = np.exp(-0.5*prod2)
    probability = const*s*ex
    probability = np.array(probability, dtype=np.float64)
    if len(probability) == 1:
        return float(probability)
    else:
        return probability


########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def E_step(X,MU,SIGMA,PI,k):
    """
    E-step - Expectation
    Calculate responsibility for each
    of the data points, for the given
    MU, SIGMA and PI.

    params:
    X = numpy.ndarray[numpy.ndarray[float]] - m x n
    MU = numpy.ndarray[numpy.ndarray[float]] - k x n
    SIGMA = numpy.ndarray[numpy.ndarray[numpy.ndarray[float]]] - k x n x n
    PI = numpy.ndarray[float] - k x 1
    k = int
    returns:
    responsibility = numpy.ndarray[numpy.ndarray[float]] - k x m
    """

    MU = np.array(MU, dtype='f')
    SIGMA = np.array(SIGMA, dtype='f')
    probs = []
    responsibility = []
    denom = 0
    if PI.ndim == 2:
        PI = np.reshape(PI, (len(PI[0],)))
    for i in range(k):
        p = prob(X, MU[i], SIGMA[i])*PI[i]
        probs.append(p)

    probs = np.array(probs)
    den = np.sum(probs, axis=0)
    responsibility = probs/den

    return responsibility

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def M_step(X, r, k):
    """
    M-step - Maximization
    Calculate new MU, SIGMA and PI matrices
    based on the given responsibilities.

    params:
    X = numpy.ndarray[numpy.ndarray[float]] - m x n
    r = numpy.ndarray[numpy.ndarray[float]] - k x m
    k = int

    returns:
    (new_MU, new_SIGMA, new_PI)
    new_MU = numpy.ndarray[numpy.ndarray[float]] - k x n
    new_SIGMA = numpy.ndarray[numpy.ndarray[numpy.ndarray[float]]] - k x n x n
    new_PI = numpy.ndarray[float] - k x 1
    """
    m_c = np.sum(r, axis=1)
    new_PI = m_c/len(X)
    new_PI = np.reshape(new_PI, (1, k))
    m_c = np.reshape(m_c, (k, 1))
    new_MU = np.dot(r, X)/m_c

    for i in range(k):
        s = X-new_MU[i]
        if i == 0:
            new_SIGMA = [np.dot(r[i]*np.transpose(s), s)/m_c[i]]
        else:
            new_SIGMA = np.vstack((new_SIGMA, [np.dot(r[i]*np.transpose(s), s)/m_c[i]]))

    return new_MU, new_SIGMA, new_PI


########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def likelihood(X, PI, MU, SIGMA, k):
    """Calculate a log likelihood of the
    trained model based on the following
    formula for posterior probability:

    log(Pr(X | mixing, mean, stdev)) = sum((i=1 to m), log(sum((j=1 to k),
                                      mixing_j * N(x_i | mean_j,stdev_j))))

    Make sure you are using natural log, instead of log base 2 or base 10.

    params:
    X = numpy.ndarray[numpy.ndarray[float]] - m x n
    MU = numpy.ndarray[numpy.ndarray[float]] - k x n
    SIGMA = numpy.ndarray[numpy.ndarray[numpy.ndarray[float]]] - k x n x n
    PI = numpy.ndarray[float] - k x 1
    k = int

    returns:
    log_likelihood = float
    """
    if PI.ndim == 2:
        PI = np.reshape(PI, (len(PI[0],)))

    for i in range(len(MU)):
        if i == 0:
            probability = PI[i]*prob(X, MU[i], SIGMA[i])
        else:
            probability = np.vstack((probability, PI[i]*prob(X, MU[i], SIGMA[i])))
    likelihood = np.sum(np.log(np.sum(probability, axis=0)))

    return likelihood
########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def train_model(X, k, convergence_function=default_convergence, initial_values = None):
    """
    Train the mixture model using the
    expectation-maximization algorithm.
    E.g., iterate E and M steps from
    above until convergence.
    If the initial_values are None, initialize them.
    Else it's a tuple of the format (MU, SIGMA, PI).
    Convergence is reached when convergence_function
    returns terminate as True,
    see default convergence_function example
    in `helper_functions.py`

    params:
    X = numpy.ndarray[numpy.ndarray[float]] - m x n
    k = int
    convergence_function = func
    initial_values = None or (MU, SIGMA, PI)

    returns:
    (new_MU, new_SIGMA, new_PI, responsibility)
    new_MU = numpy.ndarray[numpy.ndarray[float]] - k x n
    new_SIGMA = numpy.ndarray[numpy.ndarray[numpy.ndarray[float]]] - k x n x n
    new_PI = numpy.ndarray[float] - k x 1
    responsibility = numpy.ndarray[numpy.ndarray[float]] - k x m
    """
    if initial_values is None:
        initial_values = initialize_parameters(X, k)
    MU, SIGMA, PI = initial_values

    conv_ctr = 0
    conv = False
    i = 0
    while conv is False:
        if PI.ndim == 2:
            PI = np.reshape(PI, (len(PI[0],)))
        np.shape(PI)
        r = E_step(X,MU,SIGMA,PI,k)
        l = likelihood(X, PI, MU, SIGMA, k)
        new_MU, new_SIGMA, new_PI = M_step(X, r, k)
        new_PI = np.reshape(new_PI, (len(new_PI[0],)))
        new_l = likelihood(X, new_PI, new_MU, new_SIGMA, k)
        MU = new_MU
        PI = new_PI
        SIGMA = new_SIGMA
        increase_convergence_ctr = (abs(l) * 0.90 < abs(new_l) < abs(l) * 1.1)
        if increase_convergence_ctr:
            conv_ctr += 1
        else:
            conv_ctr = 0
        i += 1
        if conv_ctr > 10:
            conv = True
    return new_MU, new_SIGMA, new_PI, r
########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def cluster(r):
    """
    Based on a given responsibilities matrix
    return an array of cluster indices.
    Assign each datapoint to a cluster based,
    on component with a max-likelihood
    (maximum responsibility value).

    params:
    r = numpy.ndarray[numpy.ndarray[float]] - k x m - responsibility matrix

    return:
    clusters = numpy.ndarray[int] - m x 1
    """
    return np.argmax(r, axis=0)

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def segment(X, MU, k, r):
    """
    Segment the X matrix into k components.
    Returns a matrix where each data point is
    replaced with its max-likelihood component mean.
    E.g., return the original matrix where each pixel's
    intensity replaced with its max-likelihood
    component mean. (the shape is still mxn, not
    original image size)

    params:
    X = numpy.ndarray[numpy.ndarray[float]] - m x n
    MU = numpy.ndarray[numpy.ndarray[float]] - k x n
    k = int
    r = numpy.ndarray[numpy.ndarray[float]] - k x m - responsibility matrix

    returns:
    new_X = numpy.ndarray[numpy.ndarray[float]] - m x n
    """
    clusters = cluster(r)
    X_seg = X
#     segment image with mean values
    ones = np.ones((len(X), 3))

    for i in range(k):
        mask = clusters == i
        mask = np.vstack((mask, mask, mask))
        mask = np.transpose(mask)
        prod = mask*ones*MU[i]
        if i == 0:
            X_seg = prod
        else:
            X_seg = X_seg+prod

    return X_seg


########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def best_segment(X,k,iters, convergence_function=default_convergence):
    """Determine the best segmentation
    of the image by repeatedly
    training the model and
    calculating its likelihood.
    Return the segment with the
    highest likelihood.

    params:
    X = numpy.ndarray[numpy.ndarray[float]] - m x n
    k = int
    iters = int

    returns:
    (likelihood, segment)
    likelihood = float
    segment = numpy.ndarray[numpy.ndarray[float]]
    """
    initial_means, sigma, pi = initialize_parameters(X, k)
    init_likelihood = likelihood(X, pi, initial_means, sigma, k)
    initial_values = (initial_means, sigma, pi)
    for i in range(iters):
        new_MU, new_SIGMA, new_PI, r = train_model(X, k, convergence_function, initial_values)
        new_likelihood = likelihood(X, new_PI, new_MU, new_SIGMA, k)
        if (new_likelihood > init_likelihood):
            initial_values = (new_MU, new_SIGMA, new_PI)
            init_likelihood = new_likelihood
            new_r = r
    X_seg = segment(X, initial_values[0], k, new_r)

    return (init_likelihood, X_seg)
########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def improved_initialization(X,k):
    """
    Initialize the training
    process by setting each
    component mean using some algorithm that
    you think might give better means to start with,
    based on the mean calculate covariance matrices,
    and set each component mixing coefficient (PIs)
    to a uniform values
    (e.g. 4 components -> [0.25,0.25,0.25,0.25]).

    params:
    X = numpy.ndarray[numpy.ndarray[float]] - m x n
    k = int

    returns:
    (MU, SIGMA, PI)
    MU = numpy.ndarray[numpy.ndarray[float]] - k x n
    SIGMA = numpy.ndarray[numpy.ndarray[numpy.ndarray[float]]] - k x n x n
    PI = numpy.ndarray[float] - k x 1
    """

    initial_values = initialize_parameters(X, k)
    MU, SIGMA, PI = initial_values

    conv_ctr = 0
    conv = False
    i = 0
    while conv is not True:
        if PI.ndim == 2:
            PI = np.reshape(PI, (len(PI[0],)))
        r = E_step(X,MU,SIGMA,PI,k)
        l = likelihood(X, PI, MU, SIGMA, k)
        new_MU, new_SIGMA, new_PI = M_step(X, r, k)
        new_PI = np.reshape(new_PI, (len(new_PI[0],)))
        new_l = likelihood(X, new_PI, new_MU, new_SIGMA, k)
        MU = new_MU
        PI = new_PI
        SIGMA = new_SIGMA
        increase_convergence_ctr = (abs(l) * 0.6 < abs(new_l) < abs(l) * 1.4)
        if increase_convergence_ctr:
            conv_ctr += 1
        else:
            conv_ctr = 0
        i += 1
        if conv_ctr > 5:
            break
    return MU, SIGMA, PI
########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def new_convergence_function(previous_variables, new_variables, conv_ctr,
                             conv_ctr_cap=10):
    """
    Convergence function
    based on parameters:
    when all variables vary by
    less than 10% from the previous
    iteration's variables, increase
    the convergence counter.

    params:
    previous_variables = [numpy.ndarray[float]]
                         containing [means, variances, mixing_coefficients]
    new_variables = [numpy.ndarray[float]]
                    containing [means, variances, mixing_coefficients]
    conv_ctr = int
    conv_ctr_cap = int

    return:
    (conv_crt, converged)
    conv_ctr = int
    converged = boolean
    """

    conv_ctr_cap = 50

    increase_convergence_ctr = (abs(previous_variables[0].all()) * 0.95 <
                                abs(new_variables[0].all()) <
                                abs(previous_variables[0].all()) * 1.05)

    if increase_convergence_ctr:
        conv_ctr += 1
    else:
        conv_ctr = 0

    return conv_ctr, conv_ctr>conv_ctr_cap

def train_model_improved(X, k, convergence_function, initial_values = None):
    """
    Train the mixture model using the
    expectation-maximization algorithm.
    E.g., iterate E and M steps from
    above until convergence.
    If the initial_values are None, initialize them.
    Else it's a tuple of the format (MU, SIGMA, PI).
    Convergence is reached when convergence_function
    returns terminate as True. Use new_convergence_fuction
    implemented above.

    params:
    X = numpy.ndarray[numpy.ndarray[float]] - m x n
    k = int
    convergence_function = func
    initial_values = None or (MU, SIGMA, PI)

    returns:
    (new_MU, new_SIGMA, new_PI, responsibility)
    new_MU = numpy.ndarray[numpy.ndarray[float]] - k x n
    new_SIGMA = numpy.ndarray[numpy.ndarray[numpy.ndarray[float]]] - k x n x n
    new_PI = numpy.ndarray[float] - k x 1
    responsibility = numpy.ndarray[numpy.ndarray[float]] - k x m
    """
    MU, SIGMA, PI = improved_initialization(X,k)
    i = 0
    converged = False
    conv_ctr = 0
    while converged is False:
        if PI.ndim == 2:
            PI = np.reshape(PI, (len(PI[0],)))
        r = E_step(X,MU,SIGMA,PI,k)
        l = likelihood(X, PI, MU, SIGMA, k)
        new_MU, new_SIGMA, new_PI = M_step(X, r, k)
        new_PI = np.reshape(new_PI, (len(new_PI[0],)))
        new_l = likelihood(X, new_PI, new_MU, new_SIGMA, k)
        previous_variables = [MU, SIGMA, PI]
        MU = new_MU
        PI = new_PI
        SIGMA = new_SIGMA
        new_variables = [new_MU, new_SIGMA, new_PI]
        conv_ctr, converged = new_convergence_function(previous_variables, new_variables, conv_ctr,
                             conv_ctr_cap=10)
    return new_MU, new_SIGMA, new_PI, r

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
# Unittest below will check both of the functions at the same time.
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def bayes_info_criterion(X, PI, MU, SIGMA, k):
    """
    See description above
    params:
    X = numpy.ndarray[numpy.ndarray[float]] - m x n
    MU = numpy.ndarray[numpy.ndarray[float]] - k x n
    SIGMA = numpy.ndarray[numpy.ndarray[numpy.ndarray[float]]] - k x n x n
    PI = numpy.ndarray[float] - k x 1
    k = int

    return:
    bayes_info_criterion = int
    """
    l = likelihood(X, PI, MU, SIGMA, k)
    BIC = (k*len(MU[0])+(k*len(MU[0])*(len(MU[0])+1)/2)+k)*np.log(len(X))-2*l
    return BIC
########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def BIC_likelihood_model_test(image_matrix, comp_means):
    """Returns the number of components
    corresponding to the minimum BIC
    and maximum likelihood with respect
    to image_matrix and comp_means.

    params:
    image_matrix = numpy.ndarray[numpy.ndarray[float]] - m x n
    comp_means = list(numpy.ndarray[numpy.ndarray[float]]) - list(k x n) (means for each value of k)

    returns:
    (n_comp_min_bic, n_comp_max_likelihood)
    n_comp_min_bic = int
    n_comp_max_likelihood = int
    """
    l = []
    BICs = []
    for each in comp_means:
        PI = np.ones((1, len(each)))
        c = len(image_matrix)/np.sum(PI)
        PI = PI/np.sum(PI)
        sigma = compute_sigma(image_matrix, each)
        init_val = (each, sigma, PI)
        if PI.ndim == 2:
            PI = np.reshape(PI, (len(PI[0]),))
        MU, SIGMA, PI, r = train_model(image_matrix, len(each), convergence_function=default_convergence, initial_values=init_val)
        if PI.ndim == 2:
            PI = np.reshape(PI, (len(PI[0]),))
        l.append(likelihood(image_matrix, PI, MU, SIGMA, len(each)))
        if PI.ndim == 2:
            PI = np.reshape(PI, (len(PI[0]),))
        BICs.append(bayes_info_criterion(image_matrix, PI, MU, SIGMA, k))
    print(BICs)
    print(l)
    return (min(BICs), max(l))

def return_your_name():
    return "Adithi Minnasandran"
    raise NotImplemented()